### ISSUE TITLE
Переименовать репозиторий

### ISSUE THREAD

**Issue by TheAndrey** [mc-modding/forge-example#1]
Предлагаю дать репозиторию понятное имя, отражающее его суть, например: **Example-mod** или **Tutorial-mod**. Сейчас репозиторий называется просто «Пример» (кого/чего?)

Также следует подкорректировать описание, убрав множественное число. Сейчас оно звучит как «примеры написания модов», то есть предполагается наличие не одного мода в репозитории, а сразу нескольких. На деле у нас всего один мод с набором примеров реализации того или иного функционала – именно так должно звучать правильное описание репозитория.

**Comment by MJaroslav** [comment]
От себя добавлю, что можно разделить на ветки версий и API. Но при условии, что кто-то напишет/перенесёт остальные примеры из статей.

**Comment by Icosider** [comment]
@TheAndrey, название репозитория будет изменено, но я пока не знаю, как лучше назвать. Причина в том, что у нас не только моды, но и плагины в дальнейшем будут. Нужно общее название, а не конкретизированное. Хотя думаю плагины можно будет вынести в отдельную ветку или репозиторий.

@MJaroslav, да, будут именно ветки. Мастер ветка 1.7.10, все последующие будут по версиям делиться. Если конечно будут писать учебник и эта ноша не свалится на меня.

**Comment by Icosider** [comment]
Дополню свой комментарий ещё тем, что у нас репозиторий учебника называется "book", что тоже не вписывается 😅
@CMTV, как думаешь, необходимы ли такие изменения?

**Comment by TheAndrey** [comment]
@Icosider для примера плагина однозначно должен быть отдельный репозиторий. Для модов на других API, аля Fabric, тоже желательно завести отдельный. Примеры на Forge им не нужны. А в текущем только ветки под другие версии майна добавлять, так как это всё один продукт. Нет никакого смысла экономить на репозиториях, благо за них не приходится платить)

@CMTV не мешало бы заархивировать неактуальный репозиторий во избежание путаницы в актуальной версии: https://github.com/mc-modding/mc-modding-book

**Comment by Icosider** [comment]
@TheAndrey, да, я тебя понял. Репозиторий под плагины отдельный будет. Надо дождаться @CMTV, обсудим переименовывание репозиториев. Я сейчас ещё подготавливаю ПР с инструментами, чтобы в прод. не выкатывать, а пройти ревью. Так что надеюсь, что ты с @MJaroslav, сможете если что, подправить какие-либо недочёты.

**Comment by CMTV** [comment]
@Icosider  а во что репу `book` то переименовывать? Она же и содержит весь учебник целиком, и только его...

Изменения в репе `example` поддерживаю. Думаю, надо переименовать в `examples`, а дальше два пути: разбивать версии по разным веткам или просто создать на корневом уровне папки с версиями и API, а внутри уже моды или плагины. Ну плагины можно и в отдельный. Думаю, с ветками действительно удобно. Определитесь, как вам лучше.

@TheAndrey старый учебник заархивировал.

**Comment by TheAndrey** [comment]
> разбивать версии по разным веткам или просто создать на корневом уровне папки с версиями и API, а внутри уже моды или плагины.

Не надо учить людей плохому. Для каждого проекта должен строго свой репозиторий. Экономить на репозиториях нет никаких причин. Максимум что может содержать каждый репозиторий - это несколько версий проекта.

**Comment by CMTV** [comment]
Без проблем. Тогда решите, для какого примера эта репа и переименуем. Другие примеры действительно можно оформить в виде отдельных реп.

**Comment by Icosider** [comment]
Самое интересное, что видимо никто README.md в example не читал, там сказано о том, что версии будут на ветки разбиты. Я поддерживаю вариант @TheAndrey, что для плагинов и модов должны быть разные репы, но переименовать example лучше как предложил @CMTV.

Только обозначить надо:
forge-examples
bukkit-examples
fabric-examples

**Comment by CMTV** [comment]
Насколько я понял, @TheAndrey хочет вообще под каждый отдельный пример свою репу. То есть как-то так:

* `forge-custom-armor`
* `fabric-tile-entity`
* ...

Но это потенциально десятки реп тогда будет...

**Comment by Icosider** [comment]
Предлагаю так:
forge-examples
bukkit-examples
fabric-examples

А дальше создавать ветки: 1.7.10, 1.12.2, 1.16.5 и т.п.

**Comment by CMTV** [comment]
А сами примеры как оформлять-то? В виде одного большого мода, в котором сразу несколько статей реализуется или по папке на каждую отдельную тему?

**Comment by Icosider** [comment]
Неудобно когда на каждую статью по отдельному моду. Пусть будет как у меня это сейчас идёт. А именно один большой мод в котором реализовано всё. Мы не учим людей как писать на Java, они уже должны сами понимать, что где и как

**Comment by TheAndrey** [comment]
> Но это потенциально десятки реп тогда будет...

Пользоваться поиском и размещать ссылки никто не запрещает. Так положено делать, иначе Вы собираетесь учить людей хранить все свои разработки в одном единственном репозитории. **Пока что это репозиторий сделан правильно. Осталось добавить ветки под другие ветки Forge.** Надо показывать не только пример написания кода мода, но ещё как правильно вести историю в git.

**Comment by Icosider** [comment]
@TheAndrey, а разве сейчас история идёт неправильно? Статья добавляется -> коммит статьи

**Comment by CMTV** [comment]
Ну вообще я тоже склоняюсь к тому, что на каждую статью или набор связанных статей нужен свой репозиторий.
Внутри он разделяется на ветки.

Пример. Есть 2 статьи в учебнике, про создание моба через Fabric.
Тогда у нас тут создается репозиторий `fabric-mob` с кодом мода.
Внутри его по веткам можно разбить под разные версии майна.

Правда, под каждую статью придется настраивать рабочую среду и делать прочие рутинные штуки...

**Comment by TheAndrey** [comment]
Всё пока правильно идёт, в рамках стандартного процесса разработки. Я говорил про недопущение из мешанины коммитов от разных проектов.

**Comment by TheAndrey** [comment]
> Ну вообще я тоже склоняюсь к тому, что на каждую статью или набор связанных статей нужен свой репозиторий.

Для чего? Что мешает реализовать весь нужный функционал в рамках одного мода? Пусть люди клонируют, с помощью статей разбираются, как это работает.

**Comment by Icosider** [comment]
@CMTV, с таким подходом упахаться можно, да и пока нет людей, которые под фабрик пишут статьи. Лучше уж придерживаться общего мода в котором разработчик сможет самостоятельно найти необходимые ему классы

**Comment by Icosider** [comment]
@CMTV, с таким подходом упахаться можно, да и пока нет людей, которые под фабрик пишут статьи. Лучше уж придерживаться общего мода в котором разработчик сможет самостоятельно найти необходимые ему классы

**Comment by CMTV** [comment]
Окей не спорю. Просто у нас условно на учебник 1.12 будет один огромный мод покрывающий сразу все статьи.
И всякие `Regsitry` классы будут регать и блоки, и предметы и мобов и все это для разных статей в учебнике.

Может быть трудно из огромной кучи кода вычленить фрагменты, которые относятся к конкретной статье.

Хотя, если грамотно комменты расставлять то не особо и большая проблема... Наверное.

**Comment by Icosider** [comment]
Я прикладываю код к статьям. Код из репы скорей нужен для тех кто хочет "скачать-запустить"

**Comment by CMTV** [comment]
Окей, убедили.

@TheAndrey согласен со схемой

forge-examples
bukkit-examples
fabric-examples

с разделением на ветки по версиям?

Во что тогда эту репу переименовываем. Какое описание?

**Comment by TheAndrey** [comment]
JavaDoc комментарии писать в коде законом не запрещено. Если писать простой и понятный код без 100500 слоёв абстракции, такой проблемы не будет. Зато код в статьях будет связанный.

**У человека будет два варианта:**
* Попробовать написать мод по фрагментам из статей.
* Если не получилось, он может скачать готовый рабочий мод и его изучить, эксперементировать.

**Comment by TheAndrey** [comment]
### forge-example-mod
Именно в единственном числе, потому что мод один, а много - фич. И завести ветки под версии forge.

**Comment by Icosider** [comment]
Смысл сейчас держать пустые ветки?

**Comment by CMTV** [comment]
Ну ок, только нафига `-mod` добавлять? Что еще в теории может начинаться с `forge-example`?

Может просто `forge-example`?

**Comment by TheAndrey** [comment]
Никакого. Ответ на будущий вопрос.

**Comment by Icosider** [comment]
@CMTV, согласен, что стоит убрать `-mod`

**Comment by TheAndrey** [comment]
Можно и простое название. Но со словом mod больше людей поймёт, что это именно исходники **мода**, сделанного на Forge, а не сам API или что-то иное. Многословность должна быть, если хотите чтобы вас гарантированно правильно поняли. Мы не SMS'ки тут пишем, чтобы экономить деньги на символах...

**Comment by CMTV** [comment]
Да ладно тебе. Любой человек поймет, что `forge-example` означает именно пример мода на API Forge.
Зачем плодить лишние сущности, когда и укороченная версия звучит лаконично и понятно.

**Comment by TheAndrey** [comment]
Нужно голосование для однозначного ответа на этот вопрос)
Ладно, в будущем название всегда можно легко поменять без особых сложностей.

**Comment by CMTV** [comment]
Если голосовать, то тогда два голоса против одного получается хе-хе.
Переименовываем?

**Comment by CMTV** [comment]
Вроде все вопросы решили. Закрываю тему?

**Comment by Icosider** [comment]
@TheAndrey, @CMTV, если с переименовыванием всё решено, то зайдите в book и гляньте PR с инструментами, чтобы я потом по 500 коммитов не делал

**Comment by CMTV** [comment]
Ясность внесена. Новые ветки можно добавлять по мере готовности материала.
